# Generated by Django 4.2.3 on 2023-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deletedAt')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedId', models.IntegerField(blank=True, null=True)),
                ('linkPrecedence', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
